### ISSUE TITLE
cite spine density counter

### ISSUE THREAD

**Issue by ErbB4** [Mighty-Data-Inc/dendritic-spine-counter#2]
Hi there,
I hope you developers are doing fine.
Not sure where is the correct place to ask. I used the spine-density-counter plugin in my project and I am writing a manuscript now. It is a nice tool so I wanted to cite it properly. I didn't find any info on it. Do you perhaps know? Any Zenodo entry?

Kind regards,
Han

**Comment by omedalus** [comment]
Hello Han! We're delighted that you're using this plugin and finding it useful!

Regarding a Zenodo entry, I just created one. You can see a common DOI badge at the following URL. If you need to see the DOI badge in other formats, let us know and we will paste them.

https://zenodo.org/badge/latestdoi/363215182

As for a citation entry, we're still looking into it. We presented this plugin in a poster session at the SfN last year, but the SfN website no longer publicly lists last year's posters (nor those of previous years). We'll check if there's some kind of official citation format for them; if we can't find anything, we'll get you whatever information we can.

Best!
-Mikhail

**Comment by omedalus** [comment]
So, this isn't a citation string, but perhaps this will give you the information you need in order to construct one in the format appropriate for your paper. It's a link to the abstract of the poster presentation. It should be publicly readable. Please let me know if this helps, and I'll go ahead and close this issue.

https://www.abstractsonline.com/pp8/#!/10485/presentation/19804
